[package]
name = "rustbow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
angular-units = "0.2.4"
ansi_term = "0.12.1"
crossterm = "0.25.0"
prisma = "0.1.1"
rand = "0.8.5"
serde = "1.0.152"
